FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update 

RUN apt install -y software-properties-common

RUN add-apt-repository ppa:alessandro-strada/ppa

RUN apt update 

RUN apt install -y ffmpeg libsm6 libxext6

RUN apt install -y google-drive-ocamlfuse

RUN apt install -y python3-pip

RUN apt install -y curl

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

RUN mkdir /mnt/gdrive

COPY . /app
WORKDIR /app

RUN chmod +x /app/startup_webapp.sh

CMD ["./startup_webapp.sh"]
